1. Importe o módulo math e calcule a raiz quadrada de um número inteiro.



In [2]:
import math

numero = 16
raiz = math.sqrt(numero)
print(f"A raiz quadrada de {numero} é {raiz}")


49

2. Importe o módulo datetime e exiba a data e hora atuais.


In [1]:
from datetime import datetime

data_hora_atual = datetime.now()
print(f"A data e hora atuais são: {data_hora_atual}")

A data e hora atuais são: 2024-12-16 07:33:31.365717


3. Use o módulo string para verificar se uma string contém apenas dígitos.


In [2]:
import string

string_teste = "12345"
if string_teste.isdigit():
    print(f"A string '{string_teste}' contém apenas dígitos.")
else:
    print(f"A string '{string_teste}' não contém apenas dígitos.")



A string '12345' contém apenas dígitos.


4. Importe o módulo random e gere um número aleatório entre 1 e 100.


In [16]:
import random

numero_aleatorio = random.randint(1, 100)
print(f"Número aleatório entre 1 e 100: {numero_aleatorio}")

11


5. Importe a biblioteca numpy e crie uma array com os números de 1 a 10.


In [ ]:
import numpy as np

array = np.arange(1, 11)
print(f"Array com números de 1 a 10: {array}")


6. Escreva um programa que importe o pacote numpy e crie uma matriz de zeros
com dimensões 3x3.



In [3]:
import numpy as np

matriz_zeros = np.zeros((3, 3))
print("Matriz 3x3 de zeros:")
print(matriz_zeros)


Matriz 3x3 de zeros:
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


7. Importe a biblioteca matplotlib e crie um gráfico de barras simples com alguns
dados fictícios.


In [ ]:
import matplotlib.pyplot as plt

categorias = ['A', 'B', 'C', 'D']
valores = [10, 20, 15, 25]

plt.bar(categorias, valores, color='blue')
plt.title("Gráfico de Barras")
plt.xlabel("Categorias")
plt.ylabel("Valores")
plt.show()

8. Escreva um programa que importe o pacote matplotlib e plote a função seno.


In [ ]:
import numpy as np
import matplotlib.pyplot as plt

x = np.linspace(0, 2 * np.pi, 100)
y = np.sin(x)

plt.plot(x, y, label='Seno')
plt.title("Função Seno")
plt.xlabel("x")
plt.ylabel("sen(x)")
plt.legend()
plt.grid()
plt.show()


9. Importe o pacote requests e faça uma requisição HTTP para um URL e exiba o
código de status.


In [ ]:
import requests

url = "https://www.google.com"
response = requests.get(url)
print(f"Código de status: {response.status_code}")


10. Importe a biblioteca pandas, leia um arquivo CSV (por exemplo, "dados.csv") e
exiba as primeiras linhas do DataFrame.


In [ ]:
import pandas as pd

# Certifique-se de ter um arquivo "dados.csv" no diretório atual.
# Exemplo de conteúdo de "dados.csv":
# Nome,Idade
# João,25
# Maria,30
# Pedro,22

df = pd.read_csv("dados.csv")
print("Primeiras linhas do DataFrame:")
print(df.head())


11. Escreva um programa que importe o módulo os e imprima o diretório de trabalho
atual.


In [ ]:
import os

diretorio_atual = os.getcwd()
print(f"Diretório de trabalho atual: {diretorio_atual}")


12. Escreva um programa que importe o pacote beautifulsoup4 e faça a raspagem
de dados (web crawling) de uma página HTML.

In [4]:
import requests
from bs4 import BeautifulSoup
 
url = "https://goggle.com"  # Substitua pelo site desejado
 
response = requests.get(url) 
if response.status_code == 200: 
    soup = BeautifulSoup(response.text, 'html.parser') 
    titulo = soup.title.string
    print(f"Título da página: {titulo}") 
    links = soup.find_all('a')   
    print("\nLinks encontrados na página:")
    for link in links:
        print(link.get('href'))   
else:
    print(f"Erro ao acessar a página. Código de status: {response.status_code}")


ModuleNotFoundError: No module named 'requests'

13. Crie um módulo personalizado chamado de calculadora com uma função que
some dois números. Em seguida, importe e use essa função.



14. Suponha que estamos desenvolvendo um jogo. Uma possível organização de
pacotes e módulos poderia ser mostrada na figura abaixo.